### ISSUE TITLE
PersistentAuth is sent unconditionally

### ISSUE THREAD

**Issue by michael-o** [modauthgssapi/mod_auth_gssapi#108]
I have enabled the following:

    GssapiConnectionBound On
    GssapiSignalPersistentAuth On

Though, no authentication is bound to the connection because solely Kerberos is negotiated, the `Persistent-Auth` header is sent anyway. This header should only be send when the property is on and the authentication is actually bound to the connection. Otherwise clients receive false information.

Test logs with `curl` can be provided on request.

**Comment by frenche** [comment]
The problem is not the header, when GssapiConnectionBound is set to on then we persist authentication on the connection level for all mechanism and not only NTLM - so the header is right.

The result is similar to enabling authPersistNonNTLM registry key on MS systems (off by default).

I agree we may want to provide better granularity for which mechanism we bind to connection level.

**Comment by michael-o** [comment]
This is weird. There seems to be a change in behavior in curl 7.50.3. Though I pass the same URL multiple times, curl always closes the connection and opens a new one.

**Comment by michael-o** [comment]
Just tried with 7.39.0 on another machine. You are perfectly right. It works as designed. Curl tricked me.
