### ISSUE TITLE
Strange argument of kdb5_util

### ISSUE THREAD

**Issue by mcepl** [modauthgssapi/mod_auth_gssapi#162]
https://github.com/modauthgssapi/mod_auth_gssapi/blob/1a3598e359abf5356533c8802397c3dc357fdc9c/tests/magtests.py#L321

What is the meaning of ``-W`` parameter to ``kdb5_util``?. I cannot find it anywhere mentioned.

**Comment by frozencemetery** [comment]
It used to be the case (and still is, depending on who built it) that krb5 used a mixture of sources for entropy.
The `-W` flag, which was intentionally undocumented to avoid its use in production, instructed krb5 to use /dev/urandom wherever it would normally use /dev/random.  This is obviously ***really bad*** for anything approaching production, but at the time was considered useful for, e.g., test suites.

These days, krb5 has `getrandom()` support, and (at least in Fedora/RHEL-7) should be extremely fast after the initial PRNG seed during boot.  On new-ish versions of krb5, this flag is therefore a no-op.

**Comment by mcepl** [comment]
> This is obviously really bad for anything approaching production,

It is really? I heard from couple of people (including our colleagues who understand security a way better than me) than ``/dev/random`` is more or less snake oil and one should use ``/dev/urandom`` even for the real work. Also https://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/

**Comment by simo5** [comment]
@mcepl what is bad is to use /dev/urandom *before* it is properly seeded. After it is properly seeded use of /dev/random is definitely not necessary.
However, in the past, there was no way to know *when* urandom was properly seeded, so MIT krb5 took the safe decision to stick to /dev/random for keys. Note that MIT krb5 built on many platfroms too and guarantees of urandom were quite different on various platforms, while /dev/random tended to be uniformly an ok decision.

All this to say this is historical stuff, and, at least on Linux, we now have getrandom() usage, which is safe and that option is a noop in this case.

So, for generic testing that does not care which version of krb5 is used passing the -W option is still recommended because often VMs are misconfigured (no virtio RNG) and will just get stuck waiting for entropy on /dev/random on older krb5 releases.

**Comment by mcepl** [comment]
You are right, this conversation can serve no purpose anymore.
