### ISSUE TITLE
GssapiUseSessions seem to send duplicate cookie.

### ISSUE THREAD

**Issue by frenche** [modauthgssapi/mod_auth_gssapi#25]
This seem strange unless I missed something:

< WWW-Authenticate: Negotiate oYGzMIGwoAMKAQChCwYJKoZIhvcSAQICooGbBIGYYIGVBgkqhkiG9xIBAgICAG+BhTCBgqADAgEFoQMCAQ+idjB0oAMCAReibQRrKZpTca6SFodVsBYYpXeaSGm7MRGyK7n2Ri3Uq3qwYx8iOw47Rau0eml3Ppo4ACLwXeN4HZZ8jL9C+i1b1v+rJofXj4cyb1NG6ZypdZaXQSVbf/DrYVr+SftG1lIz6V1BX0KZf8MRzGtM6PQ=
< Set-Cookie: gssapi_session=MagBearerToken=KnTGhvBWmyG%2b78Ikm8%2bzLX8%2fgBDtHD0a%2f3N62jyzxXXmUUY09oWyNPJN0hszm0ChhlPF4Az5e%2bIfNUm1FtpKw46jsm4z0ZZlEQ%3d%3d;path=/private;httponly;secure;
< X-Powered-By: PHP/5.6.7
< Cache-Control: no-cache
< Set-Cookie: gssapi_session=MagBearerToken=KnTGhvBWmyG%2b78Ikm8%2bzLX8%2fgBDtHD0a%2f3N62jyzxXXmUUY09oWyNPJN0hszm0ChhlPF4Az5e%2bIfNUm1FtpKw46jsm4z0ZZlEQ%3d%3d;path=/private;httponly;secure;
< Content-Length: 75

My config:
<Location /private>
    GssapiUseSessions On
    Session On
    SessionCookieName gssapi_session path=/private;httponly;secure;
    GssapiBasicAuth On
    AuthType GSSAPI
    AuthName "GSSAPI Single Sign On Login"
    GssapiConnectionBound On
    Require valid-user
</Location>

**Comment by simo5** [comment]
How to set cookies is decided by the session module, it seem in some cases it decides to set the cookie twice, but as long as they are not conflicting it is harmless.

Looks like it is this bug which appears still open:
https://bz.apache.org/bugzilla/show_bug.cgi?id=55278

I'll close the issue here and suggest to ping upstream.
