### ISSUE TITLE
Delegated credentials are not created

### ISSUE THREAD

**Issue by pavel-jurasek-merck-com** [modauthgssapi/mod_auth_gssapi#26]
GssapiDelegCcacheDir is setup but i am not able to see credentials any suggestions?

**Comment by amessina** [comment]
The only thing I can think of without seeing the entire configuration snippet is to check that the apache process user has the correct perms (including SELinux perms) to read/write the directory.  I have set mine to /run/httpd/clientcaches with the following perms:

drwx------.  2 apache apache   80 May  4 18:47 clientcaches

Sidenote: I do think it would be useful to add a tmpfiles.d snippet to the packaging scripts for those systemd-based distros, similar to how mod_auth_kerb adds httpd-krbcache.conf to /lib/systemd/tmpfiles.d, which creates /run/httpd/krbcache.

**Comment by pavel-jurasek-merck-com** [comment]
@amessina Thank you fro quick answer here is my snippets bellow.
I figure out credentials are created now .. but i am not able to send remote user to my app servers.. also how can i use those files to send pre-auth request to the service? Do i missing something? 

I trying to do this:

```
CLIENT => MY_SERVER => SERVICE
```

klist /tmp/jurasek@MERCK.COM 
```
Ticket cache: FILE:/tmp/jurasek@MERCK.COM
Default principal: jurasek@MERCK.COM

Valid starting       Expires              Service principal
05/07/2015 07:42:11  05/07/2015 17:42:05  HTTP/kerberos.mywork.merck.com@MERCK.COM
05/07/2015 07:44:08  05/07/2015 17:41:03  HTTP/ts1.merck.com@MERCK.COM
	for client HTTP/kerberos.mywork.merck.com@MERCK.COM, renew until 05/14/2015 07:41:03
05/07/2015 07:41:03  05/07/2015 17:41:03  krbtgt/MERCK.COM@MERCK.COM
	for client HTTP/kerberos.mywork.merck.com@MERCK.COM, renew until 05/14/2015 07:41:03
```

krb5.conf
```
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = MERCK.COM

 allow_weak_crypto = true
 dns_lookup_kdc = true
 dns_lookup_realm = true

 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
  proxiable = true

[realms]
 MERCK.COM = {
<MERCK ip addresses>
 }

[domain_realm]
 .merck.com = MERCK.COM
 merck.com = MERCK.COM
```

apache2.conf 
```
<VirtualHost *:80>
	ServerName  kerberos.mywork.merck.com
        ServerAlias 54.40.221.55

	ServerAdmin pavel.jurasek@merck.com
	DocumentRoot /var/www/html

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory "/var/www/html">
      Options Indexes FollowSymLinks MultiViews ExecCGI
      AllowOverride None
      Require all granted
    </Directory>

     <Location />
    RewriteEngine On
    AuthType GSSAPI
    AuthName "Login"
    GssapiCredStore keytab:/etc/apache2/kerberos.mywork.service.keytab
    GssapiConnectionBound On
    Header set Persistent-Auth "true"
    GssapiUseSessions On
    Session On
    GssapiUseS4U2Proxy On
    SessionCookieName gssapi_session path=/;httponly;secure;
    GssapiUseSessions On
    GssapiUseS4U2Proxy On
    GssapiLocalName on
    Require valid-user

    RewriteCond %{LA-U:REMOTE_USER} (.+)
    RewriteRule . - [E=RU:%1]
    RequestHeader set X-Remote-User "%{RU}e" env=RU

    </Location>
    ProxyPass / http://127.0.0.1:9999/
    ProxyPassReverse / http://127.0.0.1:9999/
</VirtualHost>
```

**Comment by amessina** [comment]
I don't know what your SERVICE is but I use PHP with credentials delegated to PostgreSQL.  In the PHP script, I need to have `putenv("KRB5CCNAME={$_SERVER['KRB5CCNAME']}");`.

**Comment by simo5** [comment]
Is the client actually delegating credentials ?
Or are you counting on s4u2proxy on to cause the ticket the client has sent to be set in a krb5 ccache ?

**Comment by pavel-jurasek-merck-com** [comment]
@simo5  @amessina hi guys my problem is : 
1) Do you have some example where can i use mod_proxy with this module ? I am not able to see any remote user / KRB5CCNAME only thing what i found was that i have created /tmp/<user> delegated credential ... i use s4u2proxy but i expecting to see use case where i will be use delegated credentials and send another request with Negotiate header no?

Something like Authorization: Negotiate <token from delegated credentials> to service endpoint.

**Comment by simo5** [comment]
I do not see the GssapiDelegCcacheDir directive in your configuration, so you will not get delegated credentials nor a ccache.
Set GssapiDelegCcacheDir /path/where/apache/can/write

In that directory (which you must create) you will find files named after the user principal that authenticated, and the KRB5CCNAME variable will be set.
If you use a proxy you will need to relay that variable to the client, although that makes sense only if the client is on the same machine and has access to that directory as well.

If you want to actually use the proxy to re-authenticate to a remote party with s4u2proxy you'll have to do a lot more work.
First of all you'll need to authorize the proxy's credentials to be able to perform delegation (KDC dependant, oply AD and FreeIPA gives you this feature out of the box).
But then you'll also need to have "client" code in the proxy that knows how to use this credentials and perform a new authentication to the final destination, this is not something you can just configure in mod_proxy.

**Comment by pavel-jurasek-merck-com** [comment]
@simo5 thank you for answer! Yes i add GssapiDelegCcacheDir default path was in /tmp so it works bu i am still unable to see KRB5CCNAME and REMOTE_USER in my setup can i call you or do some skype talk ?

**Comment by pavel-jurasek-merck-com** [comment]
@simo5 i already setup my server to be trusted for delegation in AD so it should be fine.

**Comment by simo5** [comment]
So what you are saying is that you get ccache files in /tmp but KRB5CCNAME is not set ?
Where are you checking for these, on the proxy or somewhere else ?

**Comment by splashx** [comment]
> First of all you'll need to authorize the proxy's credentials to be able to perform delegation

@simo5 would you elaborate on this? Not sure if back then it was not supported, but AFAIK now MIT Kerberos supports `+ok_as_delegate flag`, is this what you had in mind back then as not supported?

**Comment by simo5** [comment]
@splashx 
This is the set of instructions we created for the freeIPA case:
https://fedorapeople.org/cgit/simo/public_git/freeipa.git/tree/daemons/ipa-kdb/README.s4u2proxy.txt
The MIT server with the default database can allow s4u2self delegation with the  +ok_to_auth_as_delegate flag, but IIRC it has no machinery to control s4u2proxy delegation.

**Comment by splashx** [comment]
@simo5 AFAIU this link is describing S4U2Self (Protocol Transition), which I also believe demands more control over who can impersonate who. I get that.. 
However I think it's a different story when doing S4U2Proxy (Constrained Delegation). I have a use case where I have a HTTP reverse proxy (Apache with mod_proxy/mod_http_proxy) in front of several HTTP services.
In my PoC:
* Reverse proxy:
  - mod_auth_gssapi configured with `GssapiUseS4U2Proxy on` (as specified [here](https://github.com/modauthgssapi/mod_auth_gssapi#gssapiuses4u2proxy) )
  - Principal set with `+ok_to_auth_as_delegate`

The web service (behind the reverse proxy) is configure to use `mod_auth_gssapi` with its own keytab for validation as the principal is set with `+ok_as_delegate`.

On the user side, **`kinit` first** and then `curl --negotiate : http://web_service.domain.com` yields the following in the reverse proxy apache logs:

```
[Thu Jul 14 11:53:05.796067 2016] [auth_gssapi:error] [pid 22760:tid 140324649993984] [client 10.10.0.208:57793] gss_accept_sec_context() failed: [Unspecified GSS failure.  Minor code may provide more information (Request ticket server HTTP/web_service.domain.com@DOMAIN.COM not found in keytab (ticket kvno 3))]
```

I understand the error - the reverse proxy can't find the keytab for `HTTP/web_service.domain.com@DOMAIN.COM` - that's fine, because the keytab is not there. But because `GssapiUseS4U2Proxy on` I would expect the reverse proxy wouldn't need  the web service's keytab (that is, the reverse proxy forwards the service ticket to the web service)...am I missing something here?


* **reverse proxy .conf:**
```
<VirtualHost *:80>	
        ServerAdmin webmaster@localhost

	LogLevel debug authz_core:trace5 auth_gssapi:debug proxy:trace5 rewrite:trace5

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	<Location />
		AuthType GSSAPI
		AuthName "GSSAPI Login"	
		
		GssapiSSLonly Off
		GssapiBasicAuth Off
		GssapiNegotiateOnce Off
		GssapiUseS4U2Proxy On
		GssapiCredStore keytab:/etc/apache2/conf/HTTP.keytab
		GssapiCredStore client_keytab:/etc/apache2/conf/HTTP.keytab
		GssapiCredStore ccache:FILE:/run/apache2/krb5ccache_HTTP
		GssapiDelegCcacheDir /run/apache2/clientcaches
	
		GssapiConnectionBound On
		Require valid-user
	</Location>

	ProxyPass / http://10.10.0.203:80/
	ProxyPassReverse / http://10.10.0.203:80/
		
	RequestHeader set X-REMOTE-USER %{REMOTE_USER}s
	RequestHeader set KRB5CCNAME %{KRB5CCNAME}s
	Header set Persistent-Auth "true"	
</VirtualHost>
```

**Comment by simo5** [comment]
If you do not want to perform authentication in the proxy, why are you configuring mod_auth_gssapi on it ?

If you are trying to terminate authentication on the proxy vs the user browser and then perform a spearate one against the service behind the proxy then mod_auth_gssapi can;t help you right now.
The ability to do delegation can only be used in conjunction with an application that uses it.

I guess it may be a reasonable feature request in some cases, but in general people simply allow Negotiate headers to be carried through and make sure all services behind the proxy have a keytab with a key assigned to a service principal named after the proxy/public DNS name.

Let me know if I misunderstood your setup.

**Comment by splashx** [comment]
> If you are trying to terminate authentication on the proxy vs the user browser and then perform a spearate one against the service behind the proxy then mod_auth_gssapi can;t help you right now.

That's the goal.  I thought that would be possible since mod_auth_gssapi has it's own client keytab (`client_keytab`) and the users keytab cached - that's the minimum requirement for S4U2Proxy AFAIU.

The use case is as follows:
```
                                           +---+
                                   +-------+   | backend for webA.domain.com  (10.0.0.10)
           +-------------------+   |       +---+
           | reverse proxy for:|   |
           |  webA.domain.com  |   |       +---+
users +----+  webB.domain.com  +-----------+   | backend for webB.domain.com  (10.0.0.20)
           |  webC.domain.com  |   |       +---+
           +-------------------+   |
              192.168.20.30        |       +---+
              rp.domain.com        +-------+   | backend for webC.domain.com  (10.0.0.30)
                                           +---+

```

Currently this works only if I import the keytabs for web[A,B,C] into the reverse proxy. That's because the user requests web[A,B,C].domain.com and during the Negotiate phase the user requests a service ticket for these domains (so the reverse proxy with `mod_auth_gssapi` must have these keytabs)
I really thought I could have one keytab for the reverse proxy which would in turn request tickets for web[A,B,C] on behalf of the user. Firstly I had overlooked the fact that the user can't be authenticated via RP keytab since the RP principal name is never explicitly entered in the HTTP request. I solved it using `rdns` and `dns_canonicalize_hostname`:

1. The user requests webA.domain.com e.g. `curl --negotiate : http://webA.domain.com`
2. The user gets the DNS A record 192.168.20.30 for  `webA.domain.com`
3. Kerberos will do a reverse dns lookup for 192.168.20.30, which will result in `rp.domain.com`
4. The user will request a service ticket for `rp.domain.com`
5. The HTTP request will contain HTTP header `Negotiate: ` related to `rp.domain.com` however the `Host:` header will contain `webA.domain.com`
6. `mod_auth_gssapi` should then request a service ticket for `webA.domain.com` using the cached user's ticket 

I works now as described until step 5. In my case, between steps 5 and 6 I would still throw mod_authnz(_ldap) in the mix (leveraging `SERVER_NAME` and `REMOTE_USER`). However step 6 is missing - what I see in apache2 `error.log` on the `webA.domain.com` backend side is:

`
[Thu Jul 14 14:18:31.601616 2016] [auth_gssapi:error] [pid 31176] [client 10.10.0.44:39056] gss_accept_sec_context() failed: [Unspecified GSS failure.  Minor code may provide more information (Request ticket server HTTP/rp.domain.com@DOMAIN.COM not found in keytab (ticket kvno 2))]
`

That's because `webA.domain.com` backend has no clue about `rp.domain.com`'s keytab.

I could run a POC now the way it is, but I think it's wiser to not to have `web[A,B,C...Z]` keytab files stored in the reverse proxy (security and scalability suffer).

**Comment by simo5** [comment]
There is no other way around, either you do authentication on the proxy and then it needs a key for each of the server names used, or the proxy does *not* do authentication and lets the actual servers do the authentication with their keys.

mod_auth_gssapi does not have a way to re-authenticate to a remote server for the proxy case.

It is something that may be attempted but would require the proxy to alter the communication between client and server behind the proxy, and perform a form sanctioned MITM.
I do not think it is really a good idea, it introduces latency and complexity in the proxy.

**Comment by splashx** [comment]
@simo5 Alright, thanks a lot.
