### ISSUE TITLE
module loading order seems to matter

### ISSUE THREAD

**Issue by rcritten** [modauthgssapi/mod_auth_gssapi#32]
When I switched from mod_auth_kerb to mod_auth_gssapi in the ipsilon project, specifically adding tests, I found that I wasn't getting an WWW-Authenticate header back so had no chance to do negotiation.

AFAICT this boiled down to the order of the modules: mod_auth_gssapi needs to be loaded before mod_auth_mellon.

**Comment by simo5** [comment]
So I took a look at this and it turns out both modules use APR_HOOK_MIDDLE as priority, so, which one gets called first really depends on the loading order.
There is a way to specify in a module that it has to be loaded before another specific module. do you think we should do this, and add an explicit ordering relative to mod_auth_mellon ?
Note that mod_auth_kerb also hooks with APR_HOOK_MIDDLE.

**Comment by rcritten** [comment]
I think it would be good to add an explicit order to avoid confusion. Note that you may be able to add an override only for a given hook and not all of them (I do this in mod_nss).

**Comment by simo5** [comment]
I think this is a mod_mellon issue in the end.
So I am going to close this one here and follow up if the mod_mellon side revelas this is not the case.
