### ISSUE TITLE
2 Anhancements...

### ISSUE THREAD

**Issue by nightman68** [modauthgssapi/mod_auth_gssapi#60]
This module is exactly that what I was looking for as a replacement for the Kerberos Module. But I have 2 issues:

#1: would it be possible to add an option to convert the UPN to lower case?
#2: I do not have root privileges on the Linux box in the company, I run rpmbuild in my home but the installation tries to install in the Apache location. It would be great when buildroot, prefix .... Are not ignored and when required package locations could be configured like for the serf library for instance?!

**Comment by simo5** [comment]
For #1 in general no, because outside of Microsoft AD kerberos principals are case sensitive, any reason why yuou need to casechange within the module ? Can't it be done in your application or even just with an apache directory to mangle the returned variable ?

For #2 the configure scripts discovers where apache's module need to be installed according to apache's devel files. If you are using system apache it will try to install in system directories.
If you need the module elsewhere I would just skip the make install step and copy the .so directly in the required place.

**Comment by nightman68** [comment]
#1 .. the purpose is that the server is accessed from Linux WS were the user just run a kinit which then uses the login name in lower case. As result you have a mixed UPN in the Kerberos token like nightman68@DOMAIN.CORP.

#2 .. OK makes sense - but I have to build the module for older Linux releases without Apache 2.4 and only older Kerberos releases available so I have to compile all by own. I modified the autoconf file for that and is working. So the configure script can be called like that: ./configure --with-spnego=/path/
