### ISSUE TITLE
mod_auth_gssapi needs mod_auth_kerb to work??

### ISSUE THREAD

**Issue by kimamil** [modauthgssapi/mod_auth_gssapi#83]
I have the following setup and cannot get mod_auth_gssapi to run correctly:

RedHat7, Apache 2.4

- generic http:// to https:// rewrite ssl.conf
- Alias intranet.company.com pointing to interalname.company.com (hostname of the Server)
- Keytab File with intranet.company.com
- vhost listening to port 443 with "ServerName intranet.company.com"
- in the `<Location /></Location>` part I have the following setup

```
AuthType GSSAPI
AuthName "Company Intranet Single-Sign-On"
GssapiBasicAuth On

Require valid-user

GssapiCredStore keytab:/etc/httpd/http_intranet.keytab
GssapiDelegCcacheDir /var/run/httpd/krbcache
```

When installing TYPO3 with the extension [realurl](https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj-t6yxsPLMAhXpJZoKHRBGBUkQFggdMAA&url=https%3A%2F%2Ftypo3.org%2Fextensions%2Frepository%2Fview%2Frealurl&usg=AFQjCNFkce2SmF3jXpN6E-1UmAb8Q3m5DA&sig2=jg4kPn2l9HW2ASC5QQXm5g) which does rewrite (mod_rewrite) GET-Parameter into shiny, human-readable URLs, the Apache Log gets filled up with the following error:

```
[auth_gssapi:error] [pid 6875] [client xxx.xxx.xxx.xxx:61373] gss_accept_sec_context() failed: [Unspecified GSS failure.  Minor code may provide more information (Request is a replay)]
```

only when installing mod_auth_kerb this issue is successfully resolved and SSO is working smoothly.

Is there a dependency to mod_auth_kerb or can you explain this behavior?

**Comment by simo5** [comment]
I do not have a crytsal ball but this is what I think is happening.

first of all you have to keep in mind that GSAPI is built to avoid replay attacks by means of a default replay cache (http://web.mit.edu/kerberos/krb5-1.12/doc/basic/rcache_def.html).

Now what I think happes is that your configuration causes apache to evaluate the Negotiate header twice in a way that mod_uth_gssapi cannot detect (we do detect subrequests and avoid double processing for exaclty this reason).

The reason why mod_auth_kerb appears to "fix" your problem is that it unconditionally disable replay cache detection for the whole process, this is a really bad property and we have not carried this behavior in mod_auth_gssapi.

If you want to disable the replay cache because " ya know whatcha doin' " you can set this environment variable before starting the apache process:
KRB5RCACHETYPE=none

But you should probably find out why there is double-processing and avoid it, it is also a performace penalty as crypto is being performed each time.

**Comment by kimamil** [comment]
Hey, you're thought experiment totally worked! But I cannot imagine that disabling the rcache is the solution to this problem.

What I also observed is, that EVERY connection does the handshake. Maybe the GssapiUseSessions Parameter might be the solution, but I cannot get it to work with the info in the readme.md, I might be missing something ...

**Comment by kimamil** [comment]
Alright, so using sessions kind of resolves the issue in Firefox (also not always). However I do experience certain instability. When using Firefox to access the page and create a session-cookie, I cannot access the page with IE afterwards, getting:

`Failed to unseal session data!`

As seen in an older issue, I set an explicit SessionKey, now I get the same error in both Browsers ... :S
